 
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: raglab-db
    environment:
      POSTGRES_DB: raglab
      POSTGRES_USER: raglab
      POSTGRES_PASSWORD: raglab
    ports:
      - "5432:5432"
    volumes:
      - raglab_db_data:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raglab -d raglab"]
      interval: 5s
      timeout: 3s
      retries: 20

  api-python:
    container_name: raglab-api-python
    build:
      context: ./apps/api-python/raglab-api-python
    environment:
      DATABASE_URL: postgres://raglab:raglab@db:5432/raglab
      RAGLAB_BACKEND: python
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  api-java:
    container_name: raglab-api-java
    build:
      context: ./apps/api-java/api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/raglab
      SPRING_DATASOURCE_USERNAME: raglab
      SPRING_DATASOURCE_PASSWORD: raglab
      RAGLAB_BACKEND: java
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  web:
    container_name: raglab-web
    build:
      context: ./apps/web/raglab
      args:
        PY_API_BASE_URL: http://nginx/api/python
        JAVA_API_BASE_URL: http://nginx/api/java
    environment:
      PY_API_BASE_URL: http://nginx/api/python
      JAVA_API_BASE_URL: http://nginx/api/java
    depends_on:
      - api-python
      - api-java
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: raglab-nginx
    depends_on:
      - web
      - api-python
      - api-java
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: raglab-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@raglab.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  raglab_db_data:
  pgadmin_data:
